name: Generate Datas

on:
  schedule:
    - cron: "* */6 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Step to create a snake animation of GitHub contributions
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: neha13rana
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step to deploy the generated SVG to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
